### PR TITLE
Additional refactorings

### PR DESCRIPTION
**Pull request by ulugbekna**

### CODE REVIEW

**Comment by gasche** [comment]
This is all good, and already mergeable. As we discussed by email, this kind of type aliases does not change the way the types are reported by the type-checker, so you may want to use more nominal types (sum types or records) to create new types instead of just aliases.

My recommendation in the present case would be to use a record for `tridirEnv`, and keep simple aliases for the rest (it's convenient to operate on them directly as maps). Feel free to do more or less if you feel like it.

**Comment by gasche** [comment]
What's the status of this PR, should we merge it now (for this you need to mark it "ready for review"), or do you still want to make some changes?

**Comment by ulugbekna** [comment]
I am still experimenting with some changes. I'll finish it up soon.

**Comment by ulugbekna** [comment]
I think that's enough of changes for this PR

**Comment by ulugbekna** [comment]
I think it is better if I make a manual merge.

**Comment by ulugbekna** [comment]
There seems to be a bug that makes the tests get stuck. I have been tracking it down for a while today. The problem is in term generation. I have a feeling that it may be cause by float gen thunk because I cannot reproduce those when I change the `ci_tests.ml` to dependent term generator with _ordinary_ float gen. Currently, `ci_tests.ml` uses `int_term_gen`s only and float generator should not be on the way, but it still gets stuck. Need to investigate further. Probably, copying the current branch and reverting commits one by one can help if it turns out that the problem is not in the float generator.

**Comment by ulugbekna** [comment]
Just a heads up: I have not fully figured out why tests would get stuck. However, I noticed that as we were creating the context for the whole test (suite) and not a single generated program, our cache, which is a list, would sometimes have a length of more than 20k elements for a 500-programs test suite. That is a (unnecessarily) huge cache that below I propose to modify. Even in case this was not the main reason the tests got stuck:

1) it would still slow down testing and increase memory overhead. These problems are solvable but read 2.
2) it was not really what we want. IMO, our main goal with repetitions is to have values that are repeated in the same generated program. We do not really need values to be repeated across several generated programs. Correct me, if I am mistaken here.

Hence, I decided to relocated the context from the test suite's closure to the program generator: a fresh cache is available for each new program generation. I have run the program repeatedly and could not reproduce the bug. (The program still ran into a 4k-element cache once) Also, these changes are coming with a clean-up described below, which I hope to push tomorrow.

Agreeably, this PR is getting too large (and error-prone), but I would want to finally have the tester working (non-buggy):
- tests do not get stuck and generation works well

 and a little saner modularity: 
- `Generators` functor is divided into module `StaticGenerators` and functor `GeneratorsWithContext` over `Context`
-module `Shrinker` does not really need to be a functor over `Context` with `StaticGenerators` present
-module `Arbitrary` does not need to be a functor either, as the Context is now local to generators

During bug hunting, I have also replaced custom test result printing to QCheck's printing, as Jan proposed some time ago.

**Comment by gasche** [comment]
Thanks for the analysis! I understand the problem that, with the shared codebase, several runs of a test will share the same cache, which is not what we intended when we discussed a design.

You mention another approach where the state is local to the program generator. Would you push the corresponding code to some branch of your clone, so that we can have a look at it?

I must say that I'm a bit surprised by how tricky it is to get the "float cache" idea right -- I suppose you are suprised as well! From a high-level perspective, one other option we have is to decide to back down and go back to not-so-good float generator for now (the best one you had without a cache). This would let us work on adding more language features, which could be useful in other ways, and revisit the problem later. It may be the case that we will have found more use-cases for generator-local state in this other part of the work, and can have a more general discussion with several use-cases when we come back to the question. I wonder what you and @jmid think of that "wait for now" idea.

**Comment by ulugbekna** [comment]
As @gasche asked, I put the changes into a [separate branch](https://github.com/ulugbekna/efftester/tree/additional_refactorings_new) on my fork. 

There are some nice changes that I mentioned above. I also added logging to the test functions that we use often and switched to a `run_tests_main`, which allows to provide cli arguments. Try: 
```sh
make tests args="--help"
make exec args="--help"
```

I switched to using a no-cache float generator. There are still tests that are very slow, e.g. try 
```sh
make exec args="--seed=4696458"
```
The test takes ~500s. Using `make tests` with the same seed results in stucks at different tests (with `exec` it is test #86, with `tests` it is #83, 85, etc.) Slow downs at different tests was also noticed in the `effmain` but not with this seed. 

I added logging to see if there is a particularly large program generated if the tests with this seed get stuck at test no86 for >400s, but the tests following #86 are not particularly large. Maybe, using a profiler would be a good idea. Also, it might also depend on synchronous the QCheck testing output is because as I added logging, sometimes test #88 is already generated but the tests cannot go over #86. One of a puzzle. (Or I am looking in wrong way)

As of new features and `'a option` and pattern matching in particular, we have discussed those a little with Jan last week during the video call, and I have been thinking about them for some time now. I spent most of the time on this issue, however.

**Comment by ulugbekna** [comment]
BTW, I have doubts on how easy it is to review non-pr branch. Let me know if I can do reviewing easier somehow (new pr or merge to this branch). Thanks for taking time to review my work :-)

**Comment by gasche** [comment]
Just to clarify, I'm not at all worried on the eventual progress of the other aspects, and I agree that it was a good choice to track the issue down and understand it. But I've been myself in the position of getting very deep into a specific subproblem; it's exciting and a bit addictive, but sometimes we also lose track of how much that matters in the large pictures. I've been lucky to have colleagues that were willing to say: "this sounds like an interesting problem, but can we also *not* solve it for now?", and I'm trying this out :-)

Re. reviewing: yes, I think that opening a new PR for the branch would be nice. Maybe it would be possible to have a PR that contains the generally useful change, that is separate from the float-generator-tuning work?

I'm curious to have a look at the tests that are taking a lot of time, I will try to do it now. From the OCaml type-checker perspective, it's in theory possible to generate very small programs that take a very long time to type-check (this is a computationally expensive problem) -- I think those programs rely on polymorphism in essential ways, and I'm not sure we generate that kind of programs yet. Same thing with compilation/execution which can in theory get very slow in some corner cases. For the `tcheck`-related test, it is possible that a slowdown comes from the type-checking algorithm in efftest. To be investigated!

**Comment by ulugbekna** [comment]
> Maybe it would be possible to have a PR that contains the generally useful change, that is separate from the float-generator-tuning work?

I would not say there is much work related to float-generator tuning. Do you mean changes in functors and modules? They fix up the buggy & not very modular code of master, don't they? 

We can probably cherry-pick this pr into several smaller ones? (Wouldn't that create more bugs/overhead during merging?) I would still be glad to split up the PR, but not sure how because all changes are quite interrelated.

**Comment by gasche** [comment]
Well, my high-level suggestion would be to drop the float cache for now, and get rid of the functors currently in master. They can stay modules if we want (not having to separate, say, Generators into two different modules is a plus).

Regarding the excessive time taken for some seeds: I instrumented the testing code to measure the time taken by each pass in https://github.com/ulugbekna/efftester/compare/additional_refactorings_new...gasche:tmp (this URL uses a "tmp" branch and may change in the future), and it appears that what takes a lot of time is neither program printing nor the actual test (checking the bytecode and native compiler on it), but the program generation step which is very slow when it generates some large programs.

From my branch above, the log file (starting from your seed value 4696458; thanks for giving it explicitly!) contains entries such as:

```ocaml
(* Next: 65 after 1.855189 *)
(* Printing: 0.000258 *)
let (x: int) = ... in print_int x;;
(* Test: 0.126464 *)
```

where the `...` part is actually a fairly large (about 8k characters; it is not *that* large) generated program. For this program it appears that generation took almost 2s, printing is instantaneous, and the actual test takes 0.1s. I'm quite sure now that the much slower example (program 86) has the same issue.

**Comment by gasche** [comment]
In fact, it may be that something stranger than that is happening:

```ocaml
(* Next: 86 after 0.000122 *)
(* Printing: 0.000032 *)
let (x: int) = int_of_string "hon" in print_int x;;
(* Test: 0.107294 *)

(* Next: 87 after 559.000976 *)
(* Printing: 0.000037 *)
let (x: int) = 95 in print_int x;;
(* Test: 0.109339 *)
```

The programs that are printed do not in any way justify the 559s delay between the end of the test 86 and the start of the test 87. It may be that some programs with extreme generation time were rejected by a precondition (and thus they don't show up here), or that something else in the test-running process is consuming the time.

**Comment by gasche** [comment]
More profiling data:

```ocaml
(* basetype_gen: 0.000043 *)
(* int *)
(* term_gen: 577.401459 *)
(* Next: 87 after 0.000060 *)
(* Printing: 0.000024 *)
let (x: int) = 95 in print_int x;;
(* Test: 0.104187 *)
```

so it seems that it is really the term generation for *this* example that is very slow, although it's not at all clear why from the output.

**Comment by gasche** [comment]
After profiling the program, I suspect that the performance problem might be caused by the `list_permute_term_gen_inner` function, which implements a very inefficient way to try to generate a term from one of the generators in a list, trying the generators in a random order.

https://github.com/ulugbekna/efftester/blob/e7f2d6f/src/efftester.ml#L1092-L1116

```ocaml
  and list_permute_term_gen_inner env goal size rules =
    let rec remove_at n xs =
      match (n, xs) with
      | 0, _ :: xs -> xs
      | n, x :: xs -> x :: remove_at (n - 1) xs
      | _ -> failwith "index out of bounds"
    in
    let elts_weighted xs =
      let _, ig =
        List.fold_left
          (fun (i, acc) (w, g) -> (i + 1, (w, Gen.pair (Gen.return i) g) :: acc))
          (0, [])
          xs
      in
      Gen.frequency ig
    in
    let to_term i = function
      | Some term -> Gen.return (Some term)
      | None ->
        let remaining_rules = remove_at i rules in
        list_permute_term_gen_inner env goal size remaining_rules
    in
    if rules = []
    then Gen.return None
else Gen.(elts_weighted rules >>= fun (i, t) -> to_term i t)
```

If I understand correctly, this algorithm first picks an argument from the list, it tries to generate a value from it, and if that fails it remove it and tries again with the shorter list. Removing a random element from a list has linear complexity, and in fact the element to choose is picked through a `Gen.frequency` call that (1) has to traverse the whole list and (2) seems to favor picking rules at the *end* of the list, making the worst-case of `remove_at` happen more often. Because you have to do this (picking then removing) for each element you try, in the worst case when none of the rules apply (and this happens very often: the generator made a foolish choice before and now there is no way to continue with a well-typed program) you have a quadratic behavior.

In the actual program the number of rules is not too large (I have no tried to measure it by logging the `List.length rules` value here), but does grow beyond the single-digits (it grows when adding more variables of suitable return type to the context). Given that this auxiliary function is called repeatedly in the term-generation loop, I can see how this could completely kill the generation performance in some cases. 

(But this is hard to test! In particular, if I tried to fix the implementation, then the random-generation choices would change and I wouldn't see the bad cases anymore with the same seed.)

So this is my best guess as to what the problem could be. @ulugbekna: *if* you are interested in looking into this performance problem, please feel free to have a look -- I'm sure there are more efficient (linear) ways to implement a function to permute the elements of a list and try them in that order, and maybe it's also possible to not do the same thing (just try one element each time; or, try an element at random a fixed number of times). This is a tricky problem, in particular I'm not sure how to test that the performance problem has gone away, given that it may occur again with another seed. On the other hand, if you prefer to work on other things for now, I think we can also decide to live with that performance issue, and just generate programs using seeds that do not hit those performance disasters.

**Comment by jmid** [comment]
I agree with your analysis @gasche. 

First `list_permute_term_gen_inner` is not a very good name for something that doesn't actually permute. This name is a historic legacy from Mathias and Patrick's original F# code with FSCheck
(that didn't have an arbitrary selector from a list of generator).

Secondly, what QCheck is missing from the `Gen.frequency`'s interface is a way to communicate which generator was chosen among a list of options. We have to know this, to later remove it in case of backtracking. The hack I made at the time was therefore to "tag" each generator with a number (`i` in the `List.fold_left` above) to record the chosen generator's index in the list.

With my MSc-student for another generator we were also bitten by this issue recently.
After thinking a bit about it, I proposed the following solution to him:

- for  `[ (4,g0); (1, g1); (3, g2); (2, g3); (1, g4) ]` compute the collected weight with a linear pass.
  in this case (4+1+3+2+1 =) 11
- use `int_range` to select a number in `[1;11]` (or `[0;10]`), say 7
- run through the weighted list and select the first generator with the right accumulated weight:
  since 4+1 < 7 <= 4+1+8 we choose `(3,g2)`
  (this way we implement our own `Gen.frequency` and can keep track of which generator was chosen)
- if the generator fails, remove it from the list and subtract its weight from the total sum 11-3=8
  and use the resulting list `[ (4,g0); (1, g1); (2, g3); (1, g4) ]`  and new sum 8 for a new iteration
  (this way we avoid recalculating new total weights after each iteration)


I'm surprised if `Gen.frequency` favors picking rules at the end of the list, @gasche . I haven't looked at the code though. I was definitely expecting it to pick with equal, but weighted chance among its argument list values 😮

**Comment by gasche** [comment]
If I read the code correctly, the `i`-th element of the `xs` list will be chosen will weight/frequency `i+1`, which means that the latter elements are more likely to be chosen than the former.

I think your proposed approach is fine, but I'm not sure why we are putting a frequency/weight on the rules in the first place. If we don't assume that some have more weight than others, then we can just use a standard algorithm to randomly permute/shuffle an array (this is easier than permuting a list) and then try the elements in the resulting order. (It's possible to be a bit more sophisticated by interleaving the tries with the shuffling, so that we don't have to draw more random numbers than necessary, but I don't think this matters a lot in practice.)

**Comment by gasche** [comment]
Well my message above was wrong of course :-) `i+1` is the accumulator of the fold, not the frequency/weight (this is `w`, reused from the input list).

If we have weights, we cannot use the standard shuffling algorithms (the [Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)), but I think that your method corresponds to a weighted version of the shuffling. This would still be more efficient with arrays rather than lists (you can swap already-picked elements at the end of the array, instead of a linear removal).

**Comment by gasche** [comment]
Dear all,

The discussions in this PR have diverged into two separate discussions:
1. how the functor structure should evolve to better localize the float generator state (if we have some)
2. what is the performance issue we observe on the CI

The two discussions are independent of each other (at first we thought that the slowdown may be related to the float cache, but we now think it isn't), and also independent of the *content* of this PR, which is a bunch of safe and reasonable changes -- I reviewed the diff and there is nothing that I don't like.

I know that @ulugbekna is preparing further PRs for (1). Woudl you be ok with merging the current PR now, so that this part is already in master and the new PRs can build on top of it? I don't see any change here that we would not want, but I'm asking (instead of merging directly) in case merging this would disrupt some things on @ulugbekna's side -- maybe you changed the history of these commits in your `additional_refactorings_new` branch?

**Comment by ulugbekna** [comment]
I think it is good to go

**Pull request merged**
