### PR TITLE
use Format to pretty-print terms

### PR DESCRIPTION
**Pull request by gasche**
This PR converts the term printer to `Format`, and uses pretty-printing hints to pretty-print terms.

I wouldn't call the end-result (nor the pretty-printing code) *readable*, but at least it is possible for humans to see the code structure. Here is one example output from the log:

```
(* 44 *) float_of_string
  (((match (fun (i: unit) -> Some (5)) () with
    | Some e -> fun (s: string) -> string_of_float 2.22044604925e-16
    | None ->
        (fun (f: string) -> fun (u: string) -> "c")
          (string_of_int ((lsl) (-1128835148867967350) 4))))
     ((^) (if (&&) true false then (^) "nxvn" "sreq" else "zeivmi")
        (if if false then true else false
         then (^) ((^) "yck" "ttohpmfq")
                (let (e: int) = (-1026767821951808209) in "kvtrkbzs")
         else if true then "cokyx" else "tqvekix")));;
```

Writing pretty-printer is a bit of a black art, although there is [some documentation of the Format module](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html). The rough idea is to visually parse `@[..@]` as a "box" (a bunch of things that should all be printed on one line, or split together), ` ` as insecable space and `@ ` as a breakable space. `@[<2>` indicates that the line breaks should add an indentation of 2.

### CODE REVIEW

**Review by ulugbekna — APPROVED** [review]
Thank you! That looks good. 

Two questions: 
1) Does `ppf` argument stand for pretty print formatter?
2) Are you satisfied by the name `term_to_str`, which converts terms to ocaml syntax?

**Comment by gasche** [comment]
1. I'm not entirely sure what `ppf` stands for (it's a convention I've reused from other places), but your suggestion seems very logical, so that may indeed be it.

2. The naming in general should be rethought, it's not so consistent to have `*_to_str` functions and `*_to_ocaml` functions that do the same thing, and some other `*_to_str` functions that go to strings. A more consistent naming convention would be `pp_foo` to pretty-print a `foo`. (I'm not sure how to rename the `term_to_str`, but it may be enough to have `string_of_pp pp_term` instead having to choose a name.) If we had raw printers that would show the complete value representation of `term` (including types and effects; instead of printing it in OCaml syntax) it could be `pp_raw_foo` or `pp_foo_raw` to make the distinction, I guess.

In this PR I didn't try to change the naming, only to change the behavior. I can give a try at improving the naming.

**Comment by ulugbekna** [comment]
I like the new printing; it is much more understandable. 
Can be merged if you are satisfied with the current status.

**Comment by gasche** [comment]
I renamed the printing function names to consistently use `pp_foo`, and got rid of the `foo_to_str` versions. I also performed a couple of refactorings on the fly -- wihch was not the greatest idea in terms of making independent changes, but so be it.

I will merge if/when the CI approves.

**Pull request merged**
