### PR TITLE
shrinking: try the minimal term at this type first

### PR DESCRIPTION
**Pull request by gasche**
On the typing bug we had for match, the shrunk counter-example was
previously as follows:

```ocaml
Some
  (List.hd
     (let var5 =
        0 <
        (let a = match None with
          | Some v -> (fun j -> "")
          | None -> (fun z -> "") in 0)
      in
      match List.hd [] with
      | Some g ->
        (match None with
        | Some n -> []
        | None -> [])
      | None -> exit 0))
```

With this change, it becomes at follows:

```ocaml
Some (List.hd
      (let a = match None with
        | Some v -> (fun x -> "")
        | None -> (fun x -> "")
       in []))
```

cc @ulugbekna -- would you like to review this PR?

### CODE REVIEW

**Comment by ulugbekna** [comment]
Wow, thanks for the PR! I'll be happy to review it (tomorrow with fresh mind) :-)

**Review by ulugbekna — APPROVED** [review]
I couldn't wait and have read the code. No flattery, that was quite enjoyable code to read (so understandable). (on a side note: did you run ocamlformat on it? it's ok if not; I can fix that)

The changes look good on their own. One thing - We eliminate all effects in the minimal term, which makes me wonder if that changes the detected buggy term too much. I need to look into `<+>` a little more to understand if those effects are restored in later shrinking or not.

**Comment by gasche** [comment]
I hadn't applied ocamlformat, and just force-pushed an ocamlformatted version. Thanks for the reminder.

The terms generated are always pure (no effects), and I think this means that they can be put anywhere and preserve the fact that the shrunk term is well-typed. Of course, any bug that relies on using a side-effectful term will not be preserved by this transformation; but it's the idea of Iter-based shrinking, we propose a lot of simplifications (from the most agressive to the smallest one), looking for the first one that can reproduce the bug, and then iterating again from that.

My understanding is that, if calling this shrinking method on the root term fails (because a part of the term, that would be erased, is really important for the bug), then what is below `<+>` will be used instead. But then, at each recursive call (that is, when trying to shrink sub-terms of the input), this technique will be tried again. Hopefully the general result is that, for all the sub-parts of the term where the strategy works, it will be applied.

**Comment by ulugbekna** [comment]
I think it is good to go and can be merged. 

Thanks once again! :-)

**Pull request merged**
